import Link from "next/link";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { CircleCheck } from "lucide-react";
import { getAdoptionReceipt, getBenchByNumber } from "@/lib/benches";
import { formatDate, formatDuration, lastCoveredDay } from "@/lib/dates";
import { buttonVariants } from "@/components/ui/button";
import { DemoNotice } from "@/components/demo-notice";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Adoption Confirmed" };

type Props = {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ adoption?: string }>;
};

export default async function ConfirmationPage({ params, searchParams }: Props) {
  const [{ id }, { adoption }] = await Promise.all([params, searchParams]);
  const bench = await getBenchByNumber(decodeURIComponent(id));
  if (!bench || !adoption) notFound();

  const receipt = await getAdoptionReceipt(adoption, bench.id);
  if (!receipt) notFound();

  const listedAs = receipt.display_name_publicly
    ? receipt.public_recognition_name?.trim() || receipt.donor_name
    : "Anonymous Donor";

  return (
    <div className="mx-auto max-w-2xl px-4 py-12 sm:px-6">
      <div className="rounded-lg border border-cream-300 bg-white p-6 text-center shadow-card sm:p-10">
        <span className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-forest-50 text-forest-700">
          <CircleCheck className="h-8 w-8" aria-hidden="true" />
        </span>
        <h1 className="mt-5 text-2xl font-semibold tracking-tight text-charcoal-900 sm:text-3xl">
          Thank you for adopting Bench {bench.bench_number}!
        </h1>
        <p className="mt-2 text-charcoal-600">Your adoption has been recorded in the demo system.</p>

        <dl className="mt-8 grid gap-x-6 gap-y-4 text-left sm:grid-cols-2">
          <Row label="Bench" value={`${bench.bench_number} · ${bench.area}`} />
          <Row label="Listed as" value={listedAs} />
          <Row label="Duration" value={formatDuration(receipt.duration_months)} />
          <Row label="Start date" value={formatDate(receipt.start_date)} />
          <Row label="Last covered day" value={formatDate(lastCoveredDay(receipt.end_date))} />
          <Row label="Available again on" value={formatDate(receipt.end_date)} />
        </dl>

        <div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row">
          <Link href={`/benches/${bench.bench_number}`} className={buttonVariants({ size: "lg" })}>
            View My Bench
          </Link>
          <Link href="/#directory" className={buttonVariants({ variant: "outline", size: "lg" })}>
            Browse More Benches
          </Link>
        </div>

        <DemoNotice className="mt-8 text-left">
          This confirmation was generated by an independent demonstration project. No payment was collected, no
          donation has been finalized, and no official adoption with Van Cortlandt Park has occurred.
        </DemoNotice>
      </div>
    </div>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-md bg-cream-50 px-3 py-2">
      <dt className="text-xs font-medium uppercase tracking-wide text-charcoal-500">{label}</dt>
      <dd className="mt-0.5 font-medium text-charcoal-900">{value}</dd>
    </div>
  );
}
